const REACT_APP_LINE_CHANNEL_ID = process.env.REACT_APP_LINE_CHANNEL_ID;
const REACT_APP_LINE_CHANNEL_SECRET = process.env.REACT_APP_LINE_CHANNEL_SECRET;
const LINE_STATE_CODE = "LINEISTHEBEST";


export const lineConfig = {
  channelId: REACT_APP_LINE_CHANNEL_ID,
  channelSecret: REACT_APP_LINE_CHANNEL_SECRET,
  lineStateCode: LINE_STATE_CODE
};